version: '2'
services:
  mobile:
    container_name: web_mobile
    image: harbor.insuite.net/framework/insuite-mobile:dev
    restart: always
    ports:
      - '80'
      - '443'
    privileged: true
    networks:
      my_net:
        aliases:
        - web_mobile

networks:
  my_net:
    external: true